### ISSUE TITLE
ValueError: Range cannot be empty (low >= high) unless no samples are taken

### ISSUE THREAD

**Issue by mengyaaa** [DLHacks/mocogan#1]
/home/lab226/Desktop/mocogan-hong/models.py:147: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  init.xavier_uniform(params)
/home/lab226/Desktop/mocogan-hong/models.py:157: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(params, 0)
!!!!!!!!!!!!!!!!!!
-12
Traceback (most recent call last):
  File "train.py", line 211, in <module>
    real_videos = random_choice()
  File "train.py", line 79, in random_choice
    video = torch.Tensor(trim(video))
  File "train.py", line 63, in trim
    start = np.random.randint(0, video.shape[1] - (T+1))
  File "mtrand.pyx", line 992, in mtrand.RandomState.randint
ValueError: Range cannot be empty (low >= high) unless no samples are taken
can any one help me?thx~

**Comment by nidhal1231** [comment]
@mengyaaa  Have you found a solution. I have the same issue. Thankyou for your help

**Comment by cjiang2000** [comment]
Bump to this thread. I also have the same issue.

**Comment by artikeshari** [comment]
Length of the video might be zero. Check the size of video.
